version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/ezcater
    docker:
      - image: circleci/ruby:2.7.5
        environment:
          - PGHOST: 127.0.0.1
          - PGUSER: postgres
      - image: circleci/postgres:11.3-alpine
        environment:
          - POSTGRES_USER: postgres
          - POSTGRES_DB: postgres_pub_sub_test
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - ruby-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile" }}-{{ checksum "activerecord-postgres_pub_sub.gemspec" }}
            - ruby-cache-{{ arch }}-{{ .Branch }}-
            - ruby-cache-

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o ./cc-test-reporter
            chmod +x ./cc-test-reporter

      # Bundle install dependencies
      - run: gem install bundler -v 1.17.3 --no-document
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: bundle clean --force
      - run: bundle exec appraisal install

      # Install Postgres client
      - run: sudo apt update && sudo apt install postgresql-client

      # Store bundle cache
      - save_cache:
          key: ruby-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile" }}-{{ checksum "activerecord-postgres_pub_sub.gemspec" }}
          paths:
            - vendor/bundle

      # Run Rubocop
      - run:
          name: RuboCop
          command: bundle exec rubocop

      # Run tests for each appraisal
      - run:
          name: rails-5.2_pg-1.1
          command: |
            bundle exec appraisal rails-5.2_pg-1.1 rspec --format RspecJunitFormatter --format progress

      - run:
          name: rails-5.2_pg-1.2
          command: |
            bundle exec appraisal rails-5.2_pg-1.2 rspec --format RspecJunitFormatter --format progress

      - run:
          name: rails-6.0_pg-1.1
          command: |
            bundle exec appraisal rails-6.0_pg-1.1 rspec --format RspecJunitFormatter --format progress

      - run:
          name: rails-6.0_pg-1.2
          command: |
            bundle exec appraisal rails-6.0_pg-1.2 rspec --format RspecJunitFormatter --format progress

      - run:
          name: rails-6.1_pg-1.1
          command: |
            bundle exec appraisal rails-6.1_pg-1.1 rspec --format RspecJunitFormatter --format progress

      - run:
          name: rails-6.1_pg-1.2
          command: |
            bundle exec appraisal rails-6.1_pg-1.2 rspec --format RspecJunitFormatter --format progress

      - run:
          name: rails-7.0_pg-1.1
          command: |
            bundle exec appraisal rails-7.0_pg-1.1 rspec --format RspecJunitFormatter --format progress

      - run:
          name: rails-7.0_pg-1.2
          command: |
            ./cc-test-reporter before-build
            bundle exec appraisal rails-7.0_pg-1.2 rspec --format RspecJunitFormatter --format progress
            ./cc-test-reporter after-build -t simplecov --exit-code $? || echo "Skipping test coverage reporting"
